sonar.projectKey=reactWebSite
sonar.projectName=reactWebSite
sonar.sourceEncoding=UTF-8

sonar.sources=server/src/main,client/src
sonar.tests=server/src/test,client/src

sonar.test.inclusions=client/src/**/*.test.js,client/src/**/*.test.jsx,client/src/**/*.spec.js,client/src/**/*.spec.jsx,client/src/setupTests.js

sonar.java.binaries=server/target/classes
sonar.java.test.binaries=server/target/test-classes

sonar.javascript.lcov.reportPaths=client/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=server/target/site/jacoco/jacoco.xml

sonar.exclusions=**/node_modules/**,**/build/**,**/target/**,client/src/index.js,client/src/reportWebVitals.js,client/src/api/mock.js
sonar.coverage.exclusions=client/src/**/*.test.js,client/src/**/*.test.jsx,client/src/**/*.spec.js,client/src/**/*.spec.jsx,client/src/setupTests.js,client/src/index.js,client/src/reportWebVitals.js,client/src/api/mock.js