apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: dev-ops
type: Opaque
stringData:
  DB_USER: devops
  DB_PASSWORD: devops
  JWT_SECRET: ddasg534tfgdsdsafdfghdfhfdfasfdsgfdsgdfhgsd
