apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: dev-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
        - name: yc-registry-secret
      containers:
        - name: client
          image: cr.yandex/crpc8d4d2ov5uvmf14qe/reactwebsite-client:3d94aaa52c4d0e235a5687bc1b9e07988b549774
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: dev-ops
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: http
      port: 80
      targetPort: 80
